"""SQLAlchemy models for the Tax Planning module.

Entities:
    - TaxRateConfig: Australian tax rates stored as configuration data
    - TaxPlan: Tax planning session per client per financial year
    - TaxScenario: What-if scenario within a tax plan
    - TaxPlanMessage: AI chat conversation message
"""

import enum
import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import BaseModel, TenantMixin

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class EntityType(str, enum.Enum):
    """Supported entity types for tax planning."""

    COMPANY = "company"
    INDIVIDUAL = "individual"
    TRUST = "trust"
    PARTNERSHIP = "partnership"


class TaxPlanStatus(str, enum.Enum):
    """Lifecycle status of a tax plan."""

    DRAFT = "draft"
    IN_PROGRESS = "in_progress"
    FINALISED = "finalised"


class DataSource(str, enum.Enum):
    """Source of financial data for a tax plan."""

    XERO = "xero"
    MANUAL = "manual"
    XERO_WITH_ADJUSTMENTS = "xero_with_adjustments"


class RiskRating(str, enum.Enum):
    """Risk level of a tax scenario strategy."""

    CONSERVATIVE = "conservative"
    MODERATE = "moderate"
    AGGRESSIVE = "aggressive"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class TaxRateConfig(BaseModel):
    """Australian tax rates, thresholds, and offsets.

    One record per financial year per rate type. Stored as configuration data
    so rates can be updated without code deployment.
    """

    __tablename__ = "tax_rate_configs"
    __table_args__ = (
        UniqueConstraint(
            "financial_year",
            "rate_type",
            name="uq_tax_rate_config_year_type",
        ),
        Index("ix_tax_rate_configs_financial_year", "financial_year"),
    )

    financial_year: Mapped[str] = mapped_column(String(10), nullable=False)
    rate_type: Mapped[str] = mapped_column(String(50), nullable=False)
    rates_data: Mapped[dict] = mapped_column(JSONB, nullable=False)
    effective_from: Mapped[datetime] = mapped_column(Date, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)


class TaxPlan(BaseModel, TenantMixin):
    """A tax planning session for a specific client and financial year.

    One plan per client per FY (enforced by unique constraint).
    Contains base financials (from Xero or manual entry), calculated tax
    position, and status tracking.
    """

    __tablename__ = "tax_plans"
    __table_args__ = (
        UniqueConstraint(
            "xero_connection_id",
            "financial_year",
            name="uq_tax_plan_connection_fy",
        ),
        Index("ix_tax_plans_tenant_status", "tenant_id", "status"),
        Index("ix_tax_plans_xero_connection_id", "xero_connection_id"),
    )

    xero_connection_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("xero_connections.id"),
        nullable=False,
    )
    financial_year: Mapped[str] = mapped_column(String(10), nullable=False)
    entity_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="draft",
        server_default="draft",
    )
    data_source: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
    )
    financials_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    tax_position: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    xero_report_fetched_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    scenarios: Mapped[list["TaxScenario"]] = relationship(
        back_populates="tax_plan",
        cascade="all, delete-orphan",
        order_by="TaxScenario.sort_order",
        lazy="selectin",
    )
    messages: Mapped[list["TaxPlanMessage"]] = relationship(
        back_populates="tax_plan",
        cascade="all, delete-orphan",
        order_by="TaxPlanMessage.created_at",
        lazy="noload",
    )


class TaxScenario(BaseModel, TenantMixin):
    """A modelled what-if scenario within a tax plan.

    Generated by the AI agent. Each scenario shows the impact of a specific
    strategy on the client's tax position.
    """

    __tablename__ = "tax_scenarios"
    __table_args__ = (Index("ix_tax_scenarios_tax_plan_id", "tax_plan_id"),)

    # Override updated_at — scenarios are immutable once created
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    tax_plan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tax_plans.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    assumptions: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    impact_data: Mapped[dict] = mapped_column(JSONB, nullable=False)
    risk_rating: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )
    compliance_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    cash_flow_impact: Mapped[Decimal | None] = mapped_column(Numeric(15, 2), nullable=True)
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Relationships
    tax_plan: Mapped["TaxPlan"] = relationship(back_populates="scenarios")


class TaxPlanMessage(BaseModel, TenantMixin):
    """Conversation message for a tax plan's AI chat session.

    Preserves full history for context-aware follow-ups and plan resumption.
    """

    __tablename__ = "tax_plan_messages"
    __table_args__ = (
        Index(
            "ix_tax_plan_messages_plan_id_created",
            "tax_plan_id",
            "created_at",
        ),
    )

    # Override updated_at — messages are immutable once created
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    tax_plan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tax_plans.id", ondelete="CASCADE"),
        nullable=False,
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    scenario_ids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)),
        nullable=False,
        default=list,
        server_default="{}",
    )
    token_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    metadata_: Mapped[dict] = mapped_column(
        "metadata",
        JSONB,
        nullable=False,
        default=dict,
        server_default="{}",
    )

    # RAG context — which knowledge chunks informed this response
    source_chunks_used: Mapped[list[dict] | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # Citation verification result for this response
    citation_verification: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    # Relationships
    tax_plan: Mapped["TaxPlan"] = relationship(back_populates="messages")
