/**
 * Generated OpenAPI types for Clairo API.
 *
 * This file is auto-generated by openapi-typescript.
 * Do not edit manually.
 *
 * Regenerate with: npm run generate-api-types
 */

// Placeholder types until generated from backend
// These will be replaced when running: npm run generate-api-types

export interface paths {
  '/': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              app: string;
              version: string;
              status: string;
              docs: string | null;
            };
          };
        };
      };
    };
  };
  '/health': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: string;
              version: string;
              environment: string;
            };
          };
        };
      };
    };
  };
  '/health/ready': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              status: string;
              checks: Record<string, string>;
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: Record<string, never>;
}
