"""Insight database models."""

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import ForeignKey, Index, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class InsightCategory(str, Enum):
    """Categories of insights."""

    COMPLIANCE = "compliance"
    QUALITY = "quality"
    CASH_FLOW = "cash_flow"
    TAX = "tax"
    STRATEGIC = "strategic"


class InsightPriority(str, Enum):
    """Priority levels for insights."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class InsightStatus(str, Enum):
    """Lifecycle status of an insight."""

    NEW = "new"
    VIEWED = "viewed"
    ACTIONED = "actioned"
    DISMISSED = "dismissed"
    RESOLVED = "resolved"
    EXPIRED = "expired"


class Insight(Base):
    """Proactive insight generated by the system.

    Insights are automatically generated by analyzers and surface
    issues that need attention without the user asking.
    """

    __tablename__ = "insights"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    tenant_id: Mapped[UUID] = mapped_column(ForeignKey("tenants.id"), nullable=False)
    client_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("xero_connections.id", ondelete="CASCADE"),
        nullable=True,
    )

    # Classification
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    insight_type: Mapped[str] = mapped_column(String(100), nullable=False)
    priority: Mapped[str] = mapped_column(String(20), nullable=False, default="medium")

    # Content
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Actions
    suggested_actions: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    related_url: Mapped[str | None] = mapped_column(String(500), nullable=True)

    # Lifecycle
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="new")
    generated_at: Mapped[datetime] = mapped_column(nullable=False, default=func.now())
    expires_at: Mapped[datetime | None] = mapped_column(nullable=True)
    action_deadline: Mapped[datetime | None] = mapped_column(
        nullable=True,
        comment="Date by which action should be taken (e.g., BAS due date, super deadline)",
    )
    viewed_at: Mapped[datetime | None] = mapped_column(nullable=True)
    actioned_at: Mapped[datetime | None] = mapped_column(nullable=True)
    dismissed_at: Mapped[datetime | None] = mapped_column(nullable=True)

    # Audit
    generation_source: Mapped[str] = mapped_column(String(50), nullable=False)
    confidence: Mapped[float | None] = mapped_column(nullable=True)
    data_snapshot: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    # Magic Zone fields (for multi-agent generated insights)
    generation_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="rule_based",
        comment="How insight was generated: rule_based, ai_single, or magic_zone",
    )
    agents_used: Mapped[list[str] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="List of agent names that contributed to this insight",
    )
    options_count: Mapped[int | None] = mapped_column(
        nullable=True,
        comment="Number of OPTIONS presented in the insight detail",
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(nullable=False, default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        nullable=False, default=func.now(), onupdate=func.now()
    )

    # Relationships
    client = relationship("XeroConnection", back_populates="insights", lazy="selectin")

    __table_args__ = (
        Index("idx_insights_tenant_status", "tenant_id", "status"),
        Index("idx_insights_tenant_priority", "tenant_id", "priority"),
        Index("idx_insights_client", "client_id", postgresql_where=client_id.isnot(None)),
        Index("idx_insights_generated", "generated_at"),
        Index("idx_insights_type_client", "insight_type", "client_id"),
    )

    def __repr__(self) -> str:
        return f"<Insight {self.insight_type}: {self.title[:30]}...>"
