/**
 * AI Export Utilities
 *
 * Enriches AI-generated content with appropriate disclaimers,
 * data freshness, and confidence metadata for safe export.
 */

import { AI_DISCLAIMER_TEXT } from '@/lib/constants';

interface ExportMetadata {
  dataFreshness?: string | null;
  confidence?: number | null;
  isEscalated?: boolean;
  escalationReason?: string | null;
}

/**
 * Enrich AI-generated content with safety metadata for export.
 *
 * Adds header disclaimer, data freshness, confidence, escalation
 * warning, and footer disclaimer to the content.
 */
export function enrichAIContentForExport(
  content: string,
  metadata: ExportMetadata = {},
): string {
  const parts: string[] = [];

  // Header disclaimer
  parts.push(`--- ${AI_DISCLAIMER_TEXT} ---`);
  parts.push('');

  // Data freshness
  if (metadata.dataFreshness) {
    try {
      const date = new Date(metadata.dataFreshness);
      const formatted = date.toLocaleDateString('en-AU', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      });
      parts.push(`Data as of: ${formatted}`);
    } catch {
      parts.push(`Data as of: ${metadata.dataFreshness}`);
    }
  }

  // Confidence
  if (metadata.confidence != null && metadata.confidence > 0) {
    parts.push(`Analysis confidence: ${Math.round(metadata.confidence * 100)}%`);
  }

  // Escalation warning
  if (metadata.isEscalated) {
    const reason = metadata.escalationReason
      ? `: ${metadata.escalationReason}`
      : '';
    parts.push(`⚠️ Professional review recommended${reason}`);
  }

  if (parts.length > 2) {
    // We have metadata beyond just the header
    parts.push('');
  }

  // Original content
  parts.push(content);

  // Footer disclaimer
  parts.push('');
  parts.push('---');
  parts.push(`Generated by Clairo AI. ${AI_DISCLAIMER_TEXT}`);

  return parts.join('\n');
}
